<a href="https://colab.research.google.com/github/aparnapandey26/sentiment-analysis/blob/main/Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Movie Sentiment Analysis**

In [ ]:
import pandas as pd
import numpy as np
import kagglehub
import os

In [ ]:

path = kagglehub.dataset_download("lakshmi25npathi/imdb-dataset-of-50k-movie-reviews")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'imdb-dataset-of-50k-movie-reviews' dataset.
Path to dataset files: /kaggle/input/imdb-dataset-of-50k-movie-reviews

In [ ]:
print(os.listdir(path))

['IMDB Dataset.csv']

In [ ]:
file_path = os.path.join(path, "IMDB Dataset.csv")
df = pd.read_csv(file_path)

In [ ]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0})

In [ ]:
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [ ]:
# One review
df['review'][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side."

**Text Cleaning**
1. Sample 10000 rows
2. Remove html tags
3. Remove special character
4. Conmverting every things to lower case
5. Removing stop words
6. Stemming

In [ ]:
df=df.sample(10000)

In [ ]:
df.shape

(10000, 2)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10000 entries, 49522 to 24708
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     10000 non-null  object
 1   sentiment  10000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 234.4+ KB

In [ ]:
import re

clean = re.compile('<.*?>')
text = re.sub(clean, '', df.iloc[2]['review'])

In [ ]:
print(text)

I thought I read somewhere that this was the last Monogram production, but whether that's true or not it doesn't matter, because if it wasn't, then it should have been. It's a deadly dull affair starring John Carradine with some gray in his hair to make himself appear like an older scientist who is experimenting with the aid of his young apprentice (Robert Shayne) in bringing the dead back to life. Every time their subjects are revived, they seem to have a whitish face like marble as they are lying strapped to the laboratory table (big deal). Carradine manages to restore his faithful dog to life after it's dead, and the mutt gains an unusual ability to walk through walls in a ghostlike fashion (wooooooooohhhh). That's about all she wrote.For an ultra-cheap Monogram quickie, this thing at least actually utilizes a more fancy-schmancy lab setup than is usually allotted. The funniest running joke in the movie is that the "older" doctor Carradine constantly refers to his "young" assistant Shayne as "m'boy" when, in fact, Carradine was actually 40 and Shayne was 45 when they made this!

In [ ]:
# Function to clean html tags

def clean_html(text):
    clean=re.compile('<.*?>')
    return re.sub(clean, '',text)

In [ ]:


df['review']=df['review'].apply(clean_html)

In [ ]:
# Converting to lower case

def convert_lower(text):
    return text.lower()

In [ ]:
df['review']=df['review'].apply(convert_lower)

In [ ]:
# To remove special character

def remove_special(text):
    x = ''
    for i in text:
        if i.isalnum():
            x = x + i
        else:
            x = x + ' '
    return x

In [ ]:
df['review']=df['review'].apply(remove_special)

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
df

                                                  review  sentiment
49522  julie brown hilariously demolishes madonna s a...          1
43404  i was in physical pain watching the eyes of th...          0
18876  i thought i read somewhere that this was the l...          0
43268  this is a simple episode ad so far after watch...          1
9200   of course you could never go into a theatre an...          1
...                                                  ...        ...
38008  no matter how you look at this movie  it is ju...          0
44037  watching this series will probably make you fe...          1
43330  they should have called this movie   adopted m...          0
18731  my wife and i never got into the movie we thou...          0
24708  okay  who was it  who gave revolver 10 out of ...          0

[10000 rows x 2 columns]

In [ ]:
stopwords.words("english")

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [ ]:
def remove_stopwords(text):
    x = []
    for i in text.split():
        if i not in stopwords.words('english'):
            x.append(i)
    y = x[:]
    x.clear()
    return y

In [ ]:
df['review']=df['review'].apply(remove_stopwords)

In [ ]:
# Perform Stemming

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [ ]:
y=[]
def stem_words(text):
    for i in text:
        y.append(ps.stem(i))
    z=y[:]
    y.clear()
    return z

In [ ]:
df['review']=df['review'].apply(stem_words)

In [ ]:
# Join back
def join_input(list_input):
    return " ".join(list_input)

In [ ]:
df['review']=df['review'].apply(join_input)

In [ ]:
df['review']

49522    juli brown hilari demolish madonna attempt roc...
43404    physic pain watch eye cast particip sham bad d...
18876    thought read somewher last monogram product wh...
43268    simpl episod ad far watch season 11 episod exc...
9200     cours could never go theatr wit type set get f...
                               ...
38008    matter look movi aw view horror unscari movi m...
44037    watch seri probabl make feel like parent felt ...
43330    call movi adopt mous brother slightli inspir s...
18731    wife never got movi thought way sloooowwww man...
24708    okay gave revolv 10 10 trip head ecstasi pipe ...
Name: review, Length: 10000, dtype: object

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
X = df['review']
y = df['sentiment']

In [ ]:
# Train and test

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 36166)
(2000, 36166)
(8000,)
(2000,)

In [ ]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
clf1=GaussianNB()
clf2=MultinomialNB()
clf3=BernoulliNB()

In [ ]:
X=cv.fit_transform(df['review']).toarray()

In [ ]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)
clf3.fit(X_train,y_train)

In [ ]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)
y_pred3=clf3.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

print(f"GaussianNB: {accuracy_score(y_test, y_pred1)}")
print(f"MultinomialNB: {accuracy_score(y_test, y_pred2)}")
print(f"BernoulliNB: {accuracy_score(y_test, y_pred3)}")

GaussianNB: 0.6235
MultinomialNB: 0.838
BernoulliNB: 0.8195